### ISSUE TITLE
Update page title

### ISSUE THREAD

**Issue by lhsazevedo** [lhsazevedo/vuetify-admin-console#5]
## First Timers Only

We know figuring out the process for contributing to an open source project can be intimidating, so we created this issue as a way for you to learn the ropes. (If you feel comfortable contributing to open source projects, please leave this issue for someone else.)

Knowledge that you'll need: HTML.

## What you will need to know

We need to update the HTML page title.

Current:
vuetify-google-admin

Desired:
Vuetify Admin Console

## Step by step

- [ ] Claim this issue by adding a comment below. Please only claim this bug if you plan on starting work in the next day or so.
- [ ] If you are a new developer and you are wondering if you need to learn Git and GitHub then here is the answer: [You Should've Learned Git Yesterday](https://codeburst.io/number-one-piece-of-advice-for-new-developers-ddd08abc8bfa).
- [ ] Create a Git branch for making your changes.
- [ ] Look for the `title` tag  in `public/index.html` and update its contents.
- [ ] Commit your changes.
- [ ] Push your changes to GitHub .
- [ ] Create a Pull Request. Mention `closes Issue #5` in the description.
- [ ] Respond to your reviewer's comments (if any).

Once approved, your changes will be merged. 

## Questions?

If you have questions ask in this issue or on your Pull Request (if you've created one).

**Comment by Thedizking** [comment]
I'd like to give this a go

**Comment by lhsazevedo** [comment]
@Thedizking Great, go ahead!
